import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Icons } from "@/components/icons";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-poppins",
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Nueve 11",
	// description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${poppins.className} h-full min-h-screen w-screen antialiased`}
			>
				{children}
				<a
					href="https://wa.me/573207338282"
					target="_blank"
					className="center-center fixed bottom-2 right-2 z-30 aspect-square w-[50px] rounded-full border-4 border-white bg-[#08B3CE] text-white shadow-lg transition-all duration-300 ease-in-out hover:scale-110 hover:shadow-xl sm:bottom-4 sm:right-4 sm:w-[69px]"
				>
					<Icons.whatsapp />
				</a>
			</body>
		</html>
	);
}
