import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} h-full min-h-screen w-screen antialiased`}
			>
				{children}
				<a
					href="https://wa.me/573207338282"
					target="_blank"
					className="fixed bottom-2 right-2 z-30 aspect-square w-[50px] hover:scale-110 sm:bottom-4 sm:right-4 sm:w-[69px]"
				>
					<Image
						src="/whatsapp.png"
						alt="logo"
						width={69}
						height={69}
						className="h-full w-full object-cover object-center"
					/>
				</a>
			</body>
		</html>
	);
}
